name: Build
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Show dotnet info 
        run: dotnet --info

      - name: Restore dotnet tools
        uses: xt0rted/dotnet-tool-restore@v1

      - name: Add dotnet-format problem matcher
        uses: xt0rted/dotnet-format-problem-matcher@v1

      - run: dotnet format --verify-no-changes

      - name: Attempt to build project
        run: dotnet build
